spring:
  datasource: # datasource 설정
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb?characterEncoding=UTF-8&rewriteBatchedStatements=true&profileSQL=true&c=Slf4JLogger
    username: sa
    password:
  h2:
    console:
      enabled: true     # h2 console 설정

logging:
  level:
    org.springframework.jdbc.core: TRACE
